openapi: 3.2.0
info:
  title: Unitary content classification API Authentication API
  description: This API is for classifying image and video files to detect various types of potentially harmful content.
  version: 1.0.0
tags:
- name: API Authentication
paths:
  /authenticate:
    post:
      tags:
      - API Authentication
      summary: Authenticate with API Key to obtain an API token
      description: 'Clients wishing to interact with the Unitary API must first authenticate by calling this endpoint with a valid API Key in the request body.


        The resulting `api_token` should be used in subsequent API requests by including a header with the format:

        ```

        Authorization: Bearer {api_token}

        ```


        The `api_token` will be valid for a period of time (default 24 hours) and should be used for all subsequent API requests until it expires, or is invalidated.


        **This endpoint is rate-limited and may return error codes if too many authentication requests are submitted within a short time frame. For this reason clients should avoid re-authenticating too often.**'
      operationId: authenticate_authenticate_post
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Body_authenticate_authenticate_post'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    LoginResponse:
      properties:
        api_token:
          type: string
          title: Api Token
        expiry:
          type: string
          format: date-time
          title: Expiry
      type: object
      required:
      - api_token
      - expiry
      title: LoginResponse
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    Body_authenticate_authenticate_post:
      properties:
        key:
          type: string
          format: password
          title: Key
          writeOnly: true
      type: object
      required:
      - key
      title: Body_authenticate_authenticate_post
  securitySchemes:
    JWTBearer:
      type: http
      scheme: bearer
      bearerFormat: JWT
